# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30)),
                ('deadline', models.TimeField(default='12:00:00')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
